# Als erstes definieren wir die host-adresse
@hosturl = https://localhost:5001

# Dies ist ein GET Request, der alle ToDos holt
GET {{hosturl}}/api/todos

###

# Nur ein ToDo holen mit korrekter Id
GET {{hosturl}}/api/todos/3

###

# Nur ein ToDo holen mit nicht vorhandenen Id
GET {{hosturl}}/api/todos/7

###

# Ein neues ToDo erstellen
POST {{hosturl}}/api/todos
content-type: application/json

{
    "taskDescription": "Ein neues ToDo"
}

###

# Ein ToDo updaten
Put {{hosturl}}/api/todos/3
content-type: application/json

{
    "isCompleted": true,
    "taskDescription": "Neuer Text für das ToDo"
}

###

# Ein ToDo löschen
Delete {{hosturl}}/api/todos/6

###

# Rufe die Webseite https://localhost:5001/swagger/index.html im Browser auf
